blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^all/$', views.allblog, name='all'),
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^register/$', views.RegistrationView.as_view(), name='register'),
    url(r'^login/$', views.log_in, name='login'),
    url(r'^logout/$', views.log_out, name='logout'),
    url(r'^post/$', views.post, name='post'),
    url(r'^(?P<post_id>[0-9]+)/comment/$', views.comment, name='comment'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^search-results/$', views.search, name='search'),
    url(r'^message/$', views.message, name='message'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Create your models here.



class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField()
    cover_photo = models.ImageField("Image", upload_to = "images/")
    post_text = models.TextField()
    post_date = models.DateTimeField('Posted on')

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.TextField()
    comment_date = models.DateTimeField('Commented on')

    def __str__(self):
        return self.comment_text

class Message(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    contact = models.CharField(max_length=50)
    message = models.TextField()

    def __str__(self):
        return self.name

blog/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User
from .models import Post


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label = "Email", required=True)
    first_name = forms.CharField(label = "First name", required = True )
    last_name = forms.CharField(label = "Last name", required = True)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2" )

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))

    def save(self, commit=True):
        data = self.cleaned_data

        user = super(RegistrationForm, self).save()
        return user


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'cover_photo', 'post_text')

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import FormView
from .forms import RegistrationForm, PostForm
from .models import Post, Comment, Message
from django.utils import timezone

def index(request):
    flag = 0
    latest_post_list = Post.objects.order_by('-post_date')[:5]
    context = {'latest_post_list': latest_post_list, 'flag': flag}
    return render(request, 'blog/index.html', context)

@login_required
def allblog(request):
    flag = 1
    latest_post_list = Post.objects.order_by('-post_date')[:]
    context = {'latest_post_list': latest_post_list, 'flag': flag}
    return render(request, 'blog/index.html', context)

@login_required
def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/detail.html', {'post': post})

@login_required
def post(request):
    if request.method == 'POST':
        a = Post(user=request.user, post_date=timezone.now())
        form = PostForm(request.POST, request.FILES, instance=a)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            print form.errors

    else:
        form = PostForm()
        return render(request, 'blog/post.html', {'form': form })

@login_required
def comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    c = Comment(comment_text=request.POST['txtArea'], comment_date=timezone.now(), user=request.user, post=post)
    c.save()
    return HttpResponseRedirect(reverse('blog:detail',args=(post.id,)))

def log_in(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('blog:index'))
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print "Invalid login details:{0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'blog/login.html')


class RegistrationView(FormView):
    template_name = 'blog/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('blog:index')
    def form_valid(self, form):
        form.save()
        return super(RegistrationView, self).form_valid(form)

@login_required
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:index'))

def about(request):
    return render(request, 'blog/about.html')

def contact(request):
    return render(request, 'blog/contact.html')

@login_required
def search(request):
    if request.method == 'POST':
        flag = 1
        latest_post_list = Post.objects.filter(title__icontains=request.POST['find']) \
                           | Post.objects.filter(user__first_name__icontains=request.POST['find']) \
                           | Post.objects.filter(user__last_name__icontains=request.POST['find'])
        context = {'latest_post_list': latest_post_list, 'flag': flag}
        return render(request, 'blog/index.html', context)

def message(request):
    if request.method == 'POST':
        m = Message(name=request.POST['name'], email=request.POST['email'], contact=request.POST['contact'], message=request.POST['message'])
        m.save()
        return HttpResponseRedirect(reverse('blog:index'))

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block head %}About Me{% endblock %}
{% block content %}

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/vyom.png' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-11 col-lg-offset-3 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1 style="color: white;
                                    text-shadow:
                                    -1px -1px 0 #000,
                                    1px -1px 0 #000,
                                    -1px 1px 0 #000,
                                    1px 1px 0 #000;">Hey there, I'm Vyom</h1>
                        <hr class="small">
                        <span class="subheading" style="color: white;
                                                        text-shadow:
                                                        -1px -1px 0 #000,
                                                        1px -1px 0 #000,
                                                        -1px 1px 0 #000,
                                                        1px 1px 0 #000;">An engineer, a web developer and an unshakable optimist.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>I'm Vyom Kapil. I'm pursuing engineering in computer science from AKGEC, Ghaziabad. I have done some work with python programming language and it's framework Django.</p>
                <p>I'm a open-hearted, fun loving person with a keen interest in following different sports like football, basketball and many more.</p>
                <blockquote>I believe that Happiness can be found in simplest of things.</blockquote>
                <p>I love the little things in life and never take myself too seriously. Laughing with friends and enjoying my family are two of my favorite things.</p>
                <p></p>
            </div>
        </div>
    </div>

    <hr>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block head %}{% endblock %} | Blog</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}" style="color: white;
                                                                            text-shadow:
                                                                            -1px -1px 0 #000,
                                                                            1px -1px 0 #000,
                                                                            -1px 1px 0 #000,
                                                                            1px 1px 0 #000;">WEBLOG</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:index' %}" style="color: white;
                                                                text-shadow:
                                                                -1px -1px 0 #000,
                                                                1px -1px 0 #000,
                                                                -1px 1px 0 #000,
                                                                1px 1px 0 #000;">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:about' %}" style="color: white;
                                                                text-shadow:
                                                                -1px -1px 0 #000,
                                                                1px -1px 0 #000,
                                                                -1px 1px 0 #000,
                                                                1px 1px 0 #000;">About</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:post' %}" style="color: white;
                                                                text-shadow:
                                                                -1px -1px 0 #000,
                                                                1px -1px 0 #000,
                                                                -1px 1px 0 #000,
                                                                1px 1px 0 #000;">Post</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:contact' %}" style="color: white;
                                                                    text-shadow:
                                                                    -1px -1px 0 #000,
                                                                    1px -1px 0 #000,
                                                                    -1px 1px 0 #000,
                                                                    1px 1px 0 #000;">Contact</a>
                    </li>
                    <li>
                        {% if user.is_authenticated %}
                                <a href="{% url 'blog:logout' %}" style="color: white;
                                                                            text-shadow:
                                                                            -1px -1px 0 #000,
                                                                            1px -1px 0 #000,
                                                                            -1px 1px 0 #000,
                                                                            1px 1px 0 #000;">Log Out</a>
                        {% else %}
                                <a href="{% url 'blog:register' %}" style="color: white;
                                                                            text-shadow:
                                                                            -1px -1px 0 #000,
                                                                            1px -1px 0 #000,
                                                                            -1px 1px 0 #000,
                                                                            1px 1px 0 #000;">REGISTER</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    {% block content %}{% endblock %}
        <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block head %}Contact Me{% endblock %}
{% block content %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/contact-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <form action="{% url 'blog:message' %}" method="post" >
                    {% csrf_token %}
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input name="name" type="text" class="form-control" placeholder="Name" id="name">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input name="email" type="email" class="form-control" placeholder="Email Address" id="email">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input name="contact" type="tel" class="form-control" placeholder="Phone Number" id="phone">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea name="message" rows="5" class="form-control" placeholder="Message" id="message"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block head %}{{post.title}}{% endblock %}
{% block content %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({{post.cover_photo.url}})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>{{post.title}}</h1>
                        <span class="meta">Posted by <a href="#">{{post.user.first_name}} {{post.user.last_name}}</a> on {{post.post_date}}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p>{{post.post_text}}</p>

                    <!-- Comments Form -->
                    <div class="well">
                        <h4>Leave a Comment:</h4>
                        <form role="form" action="{% url 'blog:comment' post.id %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <textarea class="form-control" rows="3" name="txtArea"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>

                    <hr>

                    <!-- Posted Comments -->

                    <!-- Comment -->
                    {% if post.comment_set.all %}
                        {% for comment in post.comment_set.all %}
                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="http://placehold.it/64x64" alt="">
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading">{{comment.user.first_name}} {{comment.user.last_name}}
                                        <small>{{comment.comment_date}}</small>
                                    </h4>
                                     {{comment.comment_text}}
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>No Comments are available.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </article>

    <hr>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block head %}Home{% endblock %}
{% block content %}
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>WEBLOG</h1>
                        <hr class="small">
                        <span class="subheading">Share Thoughts and Ideas.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="well">
                    <h4>Blog Search</h4>
                    <form action="{% url 'blog:search' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" name="find">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-default" type="button">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </div>
                    </form>
                    <!-- /.input-group -->
                </div>
                {% if latest_post_list %}
                    {% for post in latest_post_list %}
                        <div class="post-preview">
                            <a href="{% url 'blog:detail' post.id %}">
                                <h2 class="post-title">
                                    {{post.title}}
                                </h2>
                            </a>
                            <p class="post-meta">Posted by <a href="#">{{post.user.first_name}} {{post.user.last_name}}</a> on {{post.post_date}}</p>
                        </div>
                        <hr>
                    {% endfor %}
                {% else %}
                    <p>Oops!! No blog found.</p>
                {% endif %}
                <br />

                <!-- Pager -->
                {% if not flag %}
                    <ul class="pager">
                        <li class="next">
                            <a href="{% url 'blog:all'%}">Show all &rarr;</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>

    <hr>
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block head %}Log In{% endblock %}
{% block content %}
    <header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <hr class="small">
                        <span class="subheading">A Blogging System by Vyom</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="col-xs-4">

    </div>
    <div class="fluid-container col-xs-4">
        <form role="form" id="login_form" method="POST" action="{% url 'blog:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>
            <div class="form-group">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" id="pwd" name="password">
            </div>
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head %}Post{% endblock %}
{% block content %}
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <hr class="small">
                        <span class="subheading">A Blogging System by Vyom</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            {% crispy form %}
        </div>
        <div class="col-md-3"></div>
    </div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head %}Register{% endblock %}
{% block content %}
    <header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Blog</h1>
                        <hr class="small">
                        <span class="subheading">A Blogging System by Vyom</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% if registered %}
        <h1>Thank You for registering!</h1>
    {% else %}
        <div class="container">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <h1>Register Here!</h1>
                {% crispy form %}
                <p>Already have an account?<a href="{% url 'blog:login' %}">Log In</a></p>
            </div>
            <div class="col-md-3"></div>
        </div>
    {% endif %}
{% endblock %}